# -*- coding: utf-8 -*-
"""Marketing_Churn_Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173Ni92JRH8NOQ4tUAi96EekFhjqQjgrc
"""

# ============================================================
# Task 2: Customer Retention & Churn Analysis
# Tools: Python (Pandas, Matplotlib, Seaborn, Plotly)
# Run on: Google Colab
# ============================================================

# ── 0. Install / import libraries ──────────────────────────
# Uncomment if running for the first time on Colab
# !pip install plotly -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

# ── 1. Generate Synthetic Customer Dataset ──────────────────
np.random.seed(7)
N = 1000

plans         = ["Basic", "Standard", "Premium"]
regions       = ["North", "South", "East", "West"]
churn_reasons = ["Price", "Poor Support", "Better Competitor", "Lack of Features", "Moved Away"]
months        = ["2024-Jan","2024-Feb","2024-Mar","2024-Apr","2024-May","2024-Jun",
                 "2024-Jul","2024-Aug","2024-Sep","2024-Oct","2024-Nov","2024-Dec"]

df = pd.DataFrame({
    "CustomerID"     : range(1, N + 1),
    "Plan"           : np.random.choice(plans,   N, p=[0.40, 0.35, 0.25]),
    "Region"         : np.random.choice(regions, N),
    "Tenure_Months"  : np.random.randint(1, 60, N),
    "MonthlyCharge"  : np.round(np.random.uniform(15, 120, N), 2),
    "SupportTickets" : np.random.poisson(2, N),
    "LoginFreq_Week" : np.round(np.random.uniform(0, 14, N), 1),
    "Churned"        : np.random.choice([0, 1], N, p=[0.72, 0.28]),
    "CohortMonth"    : np.random.choice(months, N),
})

df["ChurnReason"] = np.where(
    df["Churned"] == 1,
    np.random.choice(churn_reasons, N, p=[0.32, 0.24, 0.20, 0.14, 0.10]),
    "N/A"
)
df["CLV"]    = (df["MonthlyCharge"] * df["Tenure_Months"] * (1 - df["Churned"] * 0.4)).round(2)
df["Status"] = df["Churned"].map({0: "Retained", 1: "Churned"})

print("Dataset created!")
print(f"Shape: {df.shape}  |  Churn Rate: {df['Churned'].mean()*100:.1f}%")
print(df[["Tenure_Months","MonthlyCharge","SupportTickets","CLV"]].describe().round(2))


# ── 2. GLOBAL STYLE ────────────────────────────────────────
PALETTE  = ["#6C63FF","#FF6584","#43C6AC","#F9A826","#2196F3"]
C_RETAIN = "#43C6AC"
C_CHURN  = "#FF6584"

sns.set_theme(style="darkgrid", font_scale=1.1)
plt.rcParams.update({
    "figure.facecolor": "#0F0F1A",
    "axes.facecolor"  : "#1A1A2E",
    "axes.labelcolor" : "white",
    "xtick.color"     : "white",
    "ytick.color"     : "white",
    "text.color"      : "white",
    "grid.color"      : "#2E2E4E",
    "axes.titlecolor" : "white",
    "legend.facecolor": "#1A1A2E",
    "legend.edgecolor": "#2E2E4E",
})


# ══════════════════════════════════════════════════════════
# FIGURE 1 — Churn vs Retention: Donut + Bar
# ══════════════════════════════════════════════════════════
counts = df["Churned"].value_counts()

fig1, axes = plt.subplots(1, 2, figsize=(13, 5))
fig1.patch.set_facecolor("#0F0F1A")

ax = axes[0]
ax.set_facecolor("#0F0F1A")
wedges, texts, autotexts = ax.pie(
    counts, labels=["Retained","Churned"], autopct="%1.1f%%",
    startangle=90, colors=[C_RETAIN, C_CHURN],
    wedgeprops=dict(width=0.55, edgecolor="#0F0F1A", linewidth=2),
    textprops=dict(color="white", fontsize=12)
)
for at in autotexts:
    at.set_fontsize(13); at.set_fontweight("bold")
ax.set_title("Churn vs Retention (Donut)", fontsize=13, fontweight="bold")

ax2 = axes[1]
ax2.set_facecolor("#1A1A2E")
bars = ax2.bar(["Retained","Churned"], [counts[0], counts[1]],
               color=[C_RETAIN, C_CHURN], width=0.4, edgecolor="none")
for bar, v in zip(bars, [counts[0], counts[1]]):
    ax2.text(bar.get_x() + bar.get_width()/2, v + 5, str(v),
             ha="center", va="bottom", fontsize=13, fontweight="bold", color="white")
ax2.set_ylabel("Number of Customers", fontsize=12)
ax2.set_title("Customer Count — Retained vs Churned", fontsize=13, fontweight="bold")

plt.suptitle("Overall Churn Overview", fontsize=15, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("fig1_churn_overview.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 1 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 2 — Churn Rate by Subscription Plan
# ══════════════════════════════════════════════════════════
plan_churn = (df.groupby("Plan")["Churned"].mean() * 100).reset_index()
plan_churn.columns = ["Plan","Churn Rate (%)"]
plan_churn = plan_churn.sort_values("Churn Rate (%)", ascending=False)

fig2, ax = plt.subplots(figsize=(9, 5))
fig2.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

bars = ax.bar(plan_churn["Plan"], plan_churn["Churn Rate (%)"],
              color=["#FF6584","#F9A826","#43C6AC"], edgecolor="none", width=0.45)
for bar, v in zip(bars, plan_churn["Churn Rate (%)"]):
    ax.text(bar.get_x() + bar.get_width()/2, v + 0.3, f"{v:.1f}%",
            ha="center", va="bottom", fontsize=12, fontweight="bold", color="white")
ax.axhline(df["Churned"].mean()*100, color="#FFD700", linestyle="--", linewidth=1.5,
           label=f"Overall Avg: {df['Churned'].mean()*100:.1f}%")
ax.set_ylabel("Churn Rate (%)", fontsize=12)
ax.set_title("Churn Rate by Subscription Plan", fontsize=14, fontweight="bold")
ax.legend(framealpha=0.2, labelcolor="white")
plt.tight_layout()
plt.savefig("fig2_churn_by_plan.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 2 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 3 — Churn Rate by Region (Horizontal Bar)
# ══════════════════════════════════════════════════════════
region_churn = (df.groupby("Region")["Churned"].mean() * 100).reset_index()
region_churn.columns = ["Region","Churn Rate (%)"]
region_churn = region_churn.sort_values("Churn Rate (%)", ascending=True)

fig3, ax = plt.subplots(figsize=(9, 5))
fig3.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

bars = ax.barh(region_churn["Region"], region_churn["Churn Rate (%)"],
               color=PALETTE[:4], edgecolor="none", height=0.45)
for bar, v in zip(bars, region_churn["Churn Rate (%)"]):
    ax.text(v + 0.2, bar.get_y() + bar.get_height()/2, f"{v:.1f}%",
            va="center", fontsize=12, fontweight="bold", color="white")
ax.axvline(df["Churned"].mean()*100, color="#FFD700", linestyle="--", linewidth=1.5,
           label=f"Overall Avg: {df['Churned'].mean()*100:.1f}%")
ax.set_xlabel("Churn Rate (%)", fontsize=12)
ax.set_title("Churn Rate by Region", fontsize=14, fontweight="bold")
ax.legend(framealpha=0.2, labelcolor="white")
plt.tight_layout()
plt.savefig("fig3_churn_by_region.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 3 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 4 — Top Churn Reasons (Bar)
# ══════════════════════════════════════════════════════════
reason_df = df[df["Churned"]==1]["ChurnReason"].value_counts().reset_index()
reason_df.columns = ["Reason","Count"]

fig4, ax = plt.subplots(figsize=(10, 5))
fig4.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

bars = ax.bar(reason_df["Reason"], reason_df["Count"],
              color=PALETTE, edgecolor="none", width=0.5)
for bar, v in zip(bars, reason_df["Count"]):
    ax.text(bar.get_x() + bar.get_width()/2, v + 1, str(v),
            ha="center", va="bottom", fontsize=12, fontweight="bold", color="white")
ax.set_ylabel("Number of Customers", fontsize=12)
ax.set_title("Top Reasons for Churn", fontsize=14, fontweight="bold")
plt.xticks(rotation=15, ha="right")
plt.tight_layout()
plt.savefig("fig4_churn_reasons.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 4 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 5 — Tenure Distribution: Churned vs Retained
# ══════════════════════════════════════════════════════════
fig5, ax = plt.subplots(figsize=(11, 5))
fig5.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

ax.hist(df[df["Churned"]==0]["Tenure_Months"], bins=20, color=C_RETAIN,
        alpha=0.75, label="Retained", edgecolor="none")
ax.hist(df[df["Churned"]==1]["Tenure_Months"], bins=20, color=C_CHURN,
        alpha=0.75, label="Churned",  edgecolor="none")
ax.set_xlabel("Tenure (Months)", fontsize=12)
ax.set_ylabel("Number of Customers", fontsize=12)
ax.set_title("Tenure Distribution — Churned vs Retained", fontsize=14, fontweight="bold")
ax.legend(framealpha=0.2, labelcolor="white")
plt.tight_layout()
plt.savefig("fig5_tenure_distribution.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 5 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 6 — Support Tickets vs Churn (Grouped Bar)
# ══════════════════════════════════════════════════════════
df["TicketBucket"] = pd.cut(df["SupportTickets"], bins=[-1,0,2,4,20],
                             labels=["0","1-2","3-4","5+"])
ticket_churn = df.groupby(["TicketBucket","Churned"]).size().unstack(fill_value=0)
ticket_churn.columns = ["Retained","Churned"]

fig6, ax = plt.subplots(figsize=(10, 5))
fig6.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

x = np.arange(len(ticket_churn)); w = 0.35
b1 = ax.bar(x - w/2, ticket_churn["Retained"], w, color=C_RETAIN, label="Retained", edgecolor="none")
b2 = ax.bar(x + w/2, ticket_churn["Churned"],  w, color=C_CHURN,  label="Churned",  edgecolor="none")
for bar in list(b1) + list(b2):
    h = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, h + 1, str(h),
            ha="center", va="bottom", fontsize=10, color="white")
ax.set_xticks(x); ax.set_xticklabels(ticket_churn.index, fontsize=11)
ax.set_xlabel("Support Tickets Raised", fontsize=12)
ax.set_ylabel("Number of Customers", fontsize=12)
ax.set_title("Support Tickets vs Churn", fontsize=14, fontweight="bold")
ax.legend(framealpha=0.2, labelcolor="white")
plt.tight_layout()
plt.savefig("fig6_tickets_vs_churn.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 6 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 7 — Cohort Retention Heatmap
# ══════════════════════════════════════════════════════════
cohort_ret = df.groupby("CohortMonth")["Churned"].agg(Total="count", Churned="sum").reindex(months)
cohort_ret["Retention (%)"] = ((cohort_ret["Total"] - cohort_ret["Churned"]) / cohort_ret["Total"] * 100).round(1)
heat_matrix = cohort_ret[["Retention (%)"]].T

fig7, ax = plt.subplots(figsize=(14, 3))
fig7.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

sns.heatmap(heat_matrix, annot=True, fmt=".1f", cmap="RdYlGn",
            linewidths=0.6, linecolor="#0F0F1A", ax=ax, vmin=60, vmax=85,
            cbar_kws={"label": "Retention %"},
            annot_kws={"size": 10, "weight": "bold"})
ax.set_title("Monthly Cohort Retention Rate (%)", fontsize=14, fontweight="bold")
ax.set_ylabel(""); ax.set_xlabel("")
plt.tight_layout()
plt.savefig("fig7_cohort_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 7 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 8 — Monthly Charge Distribution by Churn Status
# ══════════════════════════════════════════════════════════
fig8, ax = plt.subplots(figsize=(11, 5))
fig8.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

for status, color, label in [(0, C_RETAIN, "Retained"), (1, C_CHURN, "Churned")]:
    ax.hist(df[df["Churned"]==status]["MonthlyCharge"], bins=25,
            color=color, alpha=0.7, label=label, edgecolor="none")
ax.set_xlabel("Monthly Charge ($)", fontsize=12)
ax.set_ylabel("Number of Customers", fontsize=12)
ax.set_title("Monthly Charge Distribution — Churned vs Retained", fontsize=14, fontweight="bold")
ax.legend(framealpha=0.2, labelcolor="white")
plt.tight_layout()
plt.savefig("fig8_monthly_charge_dist.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 8 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 9 — Average CLV by Subscription Plan
# ══════════════════════════════════════════════════════════
plan_clv = df.groupby("Plan")["CLV"].mean().reset_index().sort_values("CLV", ascending=False)

fig9, ax = plt.subplots(figsize=(9, 5))
fig9.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

bars = ax.bar(plan_clv["Plan"], plan_clv["CLV"],
              color=["#6C63FF","#F9A826","#43C6AC"], edgecolor="none", width=0.4)
for bar, v in zip(bars, plan_clv["CLV"]):
    ax.text(bar.get_x() + bar.get_width()/2, v + 10, f"${v:,.0f}",
            ha="center", va="bottom", fontsize=12, fontweight="bold", color="white")
ax.set_ylabel("Avg Customer Lifetime Value ($)", fontsize=12)
ax.set_title("Average CLV by Subscription Plan", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("fig9_clv_by_plan.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 9 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 10 — Login Frequency vs Churn (Box Plot)
# ══════════════════════════════════════════════════════════
fig10, ax = plt.subplots(figsize=(9, 5))
fig10.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

data_groups = [df[df["Churned"]==k]["LoginFreq_Week"].values for k in [0,1]]
bp = ax.boxplot(data_groups, labels=["Retained","Churned"],
                patch_artist=True, widths=0.35,
                medianprops=dict(color="white", linewidth=2),
                whiskerprops=dict(color="white"),
                capprops=dict(color="white"),
                flierprops=dict(markerfacecolor="white", marker="o", alpha=0.3))
bp["boxes"][0].set_facecolor(C_RETAIN)
bp["boxes"][1].set_facecolor(C_CHURN)
ax.set_ylabel("Login Frequency (per week)", fontsize=12)
ax.set_title("Login Frequency — Retained vs Churned", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("fig10_login_vs_churn.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 10 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 11 — Feature Correlation Heatmap
# ══════════════════════════════════════════════════════════
fig11, ax = plt.subplots(figsize=(9, 6))
fig11.patch.set_facecolor("#0F0F1A"); ax.set_facecolor("#1A1A2E")

num_cols = ["Tenure_Months","MonthlyCharge","SupportTickets","LoginFreq_Week","CLV","Churned"]
corr = df[num_cols].corr()

sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
            linewidths=0.5, linecolor="#0F0F1A", ax=ax,
            annot_kws={"size": 10, "weight": "bold"},
            cbar_kws={"label": "Correlation"})
ax.set_title("Feature Correlation Heatmap", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("fig11_correlation_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()
print("Figure 11 saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 12 — Interactive: Churn by Plan & Region (Plotly)
# ══════════════════════════════════════════════════════════
plan_region = (df.groupby(["Plan","Region"])["Churned"].mean() * 100).reset_index()
plan_region.columns = ["Plan","Region","Churn Rate (%)"]

fig12 = px.bar(plan_region, x="Region", y="Churn Rate (%)", color="Plan",
               barmode="group",
               color_discrete_sequence=["#6C63FF","#FF6584","#43C6AC"],
               title="Churn Rate by Plan & Region (Interactive)",
               template="plotly_dark", text_auto=".1f")
fig12.update_layout(paper_bgcolor="#0F0F1A", font=dict(color="white"))
fig12.write_html("fig12_churn_plan_region.html")
fig12.show()
print("Figure 12 (interactive HTML) saved.")


# ══════════════════════════════════════════════════════════
# FIGURE 13 — Interactive: Tenure vs CLV Bubble Chart
# ══════════════════════════════════════════════════════════
fig13 = px.scatter(
    df.sample(400, random_state=1),
    x="Tenure_Months", y="CLV",
    color="Status",
    color_discrete_map={"Retained": C_RETAIN, "Churned": C_CHURN},
    size="MonthlyCharge",
    hover_data=["Plan","Region","SupportTickets"],
    title="Tenure vs CLV — Bubble Size = Monthly Charge (Interactive)",
    template="plotly_dark", opacity=0.75, size_max=20,
)
fig13.update_layout(paper_bgcolor="#0F0F1A", font=dict(color="white"))
fig13.write_html("fig13_tenure_clv_scatter.html")
fig13.show()
print("Figure 13 (interactive HTML) saved.")


# ── 4. KEY INSIGHTS & RECOMMENDATIONS ─────────────────────
overall_churn  = df["Churned"].mean() * 100
best_plan      = plan_churn.sort_values("Churn Rate (%)").iloc[0]["Plan"]
worst_plan     = plan_churn.sort_values("Churn Rate (%)", ascending=False).iloc[0]["Plan"]
top_reason     = reason_df.iloc[0]["Reason"]
avg_tenure_ch  = df[df["Churned"]==1]["Tenure_Months"].mean()
avg_tenure_rt  = df[df["Churned"]==0]["Tenure_Months"].mean()

print("\n" + "="*62)
print("       KEY INSIGHTS & RECOMMENDATIONS")
print("="*62)
print(f"\n  Overall Churn Rate       : {overall_churn:.1f}%")
print(f"  Avg Tenure (Churned)     : {avg_tenure_ch:.1f} months")
print(f"  Avg Tenure (Retained)    : {avg_tenure_rt:.1f} months")
print(f"  Lowest Churn Plan        : {best_plan}")
print(f"  Highest Churn Plan       : {worst_plan}")
print(f"  Top Churn Reason         : {top_reason}")
print(f"""
  Actionable Recommendations:
  1. Target early churners: Most churn occurs in first {int(avg_tenure_ch)} months.
     Assign a dedicated success manager for months 1-3.
  2. Review '{worst_plan}' plan — highest churn rate.
     Add exclusive perks or loyalty discounts to improve stickiness.
  3. Address '{top_reason}' — the #1 churn driver.
     Launch a proactive outreach or competitor comparison campaign.
  4. Re-engage customers with low login frequency (< 3/week)
     — strong early predictor of upcoming churn.
  5. Fast-track support resolution — high ticket volume
     correlates strongly with churn.
  6. Build loyalty rewards for high CLV customers to maximize LTV.
""")
print("="*62)
print("All figures saved! Open .html files for interactive charts.")